# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ip6_pb2 as ip6__pb2


class PacketStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendPacket = channel.unary_unary(
                '/ip6.Packet/sendPacket',
                request_serializer=ip6__pb2.PacketRequest.SerializeToString,
                response_deserializer=ip6__pb2.PacketRecieved.FromString,
                )


class PacketServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendPacket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PacketServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendPacket': grpc.unary_unary_rpc_method_handler(
                    servicer.sendPacket,
                    request_deserializer=ip6__pb2.PacketRequest.FromString,
                    response_serializer=ip6__pb2.PacketRecieved.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ip6.Packet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Packet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendPacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ip6.Packet/sendPacket',
            ip6__pb2.PacketRequest.SerializeToString,
            ip6__pb2.PacketRecieved.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HeartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendHeartBeat = channel.unary_unary(
                '/ip6.Heart/sendHeartBeat',
                request_serializer=ip6__pb2.Artery.SerializeToString,
                response_deserializer=ip6__pb2.Vein.FromString,
                )


class HeartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendHeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendHeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.sendHeartBeat,
                    request_deserializer=ip6__pb2.Artery.FromString,
                    response_serializer=ip6__pb2.Vein.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ip6.Heart', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Heart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendHeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ip6.Heart/sendHeartBeat',
            ip6__pb2.Artery.SerializeToString,
            ip6__pb2.Vein.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
